name: CI/CD for Scrapy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SCRAPYD_HOST: ${{ secrets.SCRAPYD_HOST }}
      SCRAPYD_USERNAME: ${{ secrets.SCRAPYD_USERNAME }}
      SCRAPYD_PASSWORD: ${{ secrets.SCRAPYD_PASSWORD }}
      SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install scrapyd-client pytest
      - name: Run tests
        run: pytest src/rightmove/tests/
      - name: Add Scrapyd auth
        run: |
          echo "machine ${{ secrets.SCRAPYD_HOST }} login ${{ secrets.SCRAPYD_USERNAME }} password ${{ secrets.SCRAPYD_PASSWORD }}" >> ~/.netrc
      - name: Deploy to Scrapyd
        run: |
          cd src/rightmove
          scrapyd-deploy production
